### ISSUE TITLE
Add some selenium tests

### ISSUE THREAD

**Issue by xmnlab** [thegraphnetwork/EpiGraphHub#179]
it would be nice to have some simple selenium tests just to run some smoke tests

**Comment by xmnlab** [comment]
for gh actions workflow:

```yaml
- uses: nanasess/setup-chromedriver@v1

      # https://github.com/nanasess/setup-chromedriver
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
```
